logging:
  level:
    org.springframework.ai.openai: debug
    com.openai: debug
#    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
    org.springframework.ai.vectorstore.SimpleVectorStore: warn
    root: info

spring:
  ai:
    model:
      chat: openai
    openai:
      base-url: http://127.0.0.1:8001/v1
      api-key: sk-lm-29jxIiYh:4r3KV4gLzZLwM7XcssBj
      chat:
        model: claude-opus-4.6
        temperature: 0.7
      embedding:
        model: text-embedding-embeddinggemma-300m-qat
        # 向量维度
        dimensions: 1024
    vectorstore:
      chroma:
        client:
          host: http://192.168.100.100
          port: 8000